nix-community/emacs-overlay

patches/tramp-detect-wrapped-gvfsd.patch

Recently TRAMP removed `tramp-compat-process-running-p`.
See: https://github.com/emacs-mirror/emacs/commit/d3ead375092e2690c1d1d6a5dd82e6e89cdf4f4c

Update gvfsd patch

---

default.nix

This helps with figuring out which repository revision is one running, so one can report that with their bug reports.

Embed emacs repository revision, and branch information at build time

---

default.nix

Tested on `emacsUnstable` (however `emacsGit` should also work). HarfBuzz is enabled by default on Emacs 27+ so there is no need to change build flags.
Result:
```
emacs   version    27.0.90
features   XPM JPEG TIFF GIF PNG RSVG SOUND DBUS GSETTINGS GLIB NOTIFY INOTIFY LIBSELINUX GNUTLS LIBXML2 FREETYPE HARFBUZZ M17N_FLT LIBOTF XFT ZLIB TOOLKIT_SCROLL_BARS GTK3 X11 XDBE XIM MODULES THREADS LIBSYSTEMD JSON PDUMPER GMP
build      abr 05, 2020
buildopts  (--prefix=/nix/store/pwv8y5jrzlqczsnqvfyklasihap2cavw-emacs-27.0.90 --disable-build-details --with-modules --with-x-toolkit=gtk3 --with-xft CFLAGS=-DMAC_OS_X_VERSION_MAX_ALLOWED=101200)
windowsys  x
daemonp    server-running
```
Fix issue https://github.com/nix-community/emacs-overlay/issues/16.

Add harfbuzz to build inputs

---

default.nix
repos/org/org-generated.nix

This is a follow-up to https://github.com/NixOS/nixpkgs/pull/87125. org-generated.nix was generated by running `NIX_PATH=nixpkgs=https://github.com/NixOS/nixpkgs-channels/archive/nixos-unstable.tar.gz ./update` (and then manually `git add`ed), so this should work fine with the cronjob.

Reenable orgPackages

---

README.org
default.nix
repos/emacs/emacs-feature_native-comp.json
repos/emacs/update

Adds the `native-comp` branch of Emacs adding native compilation.
This is to be considered experimental and no guarantees are provided.
Closes https://github.com/nix-community/emacs-overlay/issues/29
cc @bhipple

Add emacs native-comp branch (emacsGcc)

---

README.org
default.nix
elisp.nix
packreq.nix
parse.nix

This provides a mechanism for creating an Emacs closure that contains the runtime dependencies for a given Emacs package source file, by inspecting its `Package-Requires` header.
I wanted to explore using emacs-overlay to simplify the process of provisioning tailored Emacsen for testing packages in CI and locally, as an alternative to using/integrating with Cask: this is the result, and I'm quite excited about it. Further work could add support for parsing `-pkg.el` files, or even `Cask` files, though it's pretty annoying to use `builtins.*` to dig through sexps.
There's an opportunity to somewhat unify the interface between the functions in `elisp.nix` and `packreq.nix`, but it wasn't immediately clear how best to factor that to avoid it getting clunky or unnatural, so I thought I'd post …

Add emacsWithPackagesFromPackageRequires

---

elisp.nix
parse.nix

Use the native Org mode parsing capabilities of `fromElisp` for Org babel file support. Fixes #44 without the downsides of IFD.
cc @Sorixelle @alexvorobiev

Use the native Org mode parsing capabilities of fromElisp

---

README.org
elisp.nix
parse.nix

Add an option to tangle Org babel code blocks by default, as suggested in #52. `fromElisp` has also been updated to support `#+HEADER:`-lines.
cc @alexvorobiev @terlar

Add `alwaysTangle` argument to emacsWithPackagesFromUsePackage

---

.ci/cron

The `nixpkgs-channels` repo is deprecated and no longer updated.
Fixes #78

ci: Update nixpkgs URL, nixpkgs-channels -> nixpkgs

---

hydra/default.nix
hydra/spec.json

Looks like these were missed in an earlier commit. See issue #78.

Stop using deprecated "nixpkgs-channels" repo (again)

---

README.org

I added them as a section under the usage heading

README: add binary cache instructions

---

README.org
elisp.nix
parse.nix

Add [`leaf`](https://github.com/conao3/leaf.el) as an alternative to `use-package` in `emacsWithPackagesFromUsePackage`. Automatically add the used package manager(s) to the package set.
Alternative to #82.
cc @adithyaov

Allow `leaf` to be used as an alternative to `use-package` in `emacsWithPackagesFromUsePackage`

---

default.nix

I don't exactly understand why, but this fixes native compilation of packages for me. See https://github.com/nix-community/emacs-overlay/pull/105#issuecomment-770427371.

use overrideAttrs' argument instead of referring to derivation

---

.github/workflows/ci.yml

The update script tries to commit the changes to each repo individually, but fails if user info isn't configured.
cc @nuance

ci: Configure git before running the update script

---

repos/emacs/emacs-unstable.json

The sha256 doesn't change because 27.2-rc2 is actually the same as
27.2.

emacs-unstable: Change rev from emacs-27.2-rc2 to emacs-27.2

---

hydra/default.nix

Right now, one has no cache for the nixos stable channel that was recently changed to 21.05, I hope this fixes that.

stable nixpkgsRelease: 20.09->21.05

---

default.nix

https://github.com/NixOS/nixpkgs/commit/9140d4b06ff09bce8dd8e384eeef832e7811d288
broke certain builds that were not properly passing commit as an
argument to the builder. This also caused the exwm xelb (i. e.
emacsPackages.xelb) to fail. Since we have the commit as
`repoMeta.rev` anyways, passing it properly is trivial.

mkExDrv: properly pass commit as required by recent package-build

---

repos/emacs/update

If more than the specified amount of time has passed, then there is no
tag, and nothing actually gets downloaded by `nix-prefetch-url`.
In this case, slightly more than 6 months (the previously specified time) have passed since the release of 27.2, so the build fails to get any release version, which is why no updates to Emacs have occurred here since last week.
28.0.91 should come out soon, so I think 9 months may be appropriate.
cc @talyz

* repos/emacs/update: fetch more commits in git clone

---

default.nix
patches/tramp-detect-wrapped-gvfsd-28.patch
repos/emacs/emacs-emacs-28.json
repos/emacs/update

As the release branch for emacs 28 has been cut, and emacsGit now builds emacs
29, let's add a way to track emacs 28.
This is very similar to #182, except that it keeps emacsGit building emacs
29.
Closes #185

Add emacs 28

---

hydra/default.nix

NixOS stable was bumped to 21.11 a few days ago and right now there are no cached builds for it, this change should fix that.

stable nixpkgsRelease: 21.05 -> 21.11

---

default.nix

This should result in much better binary cache hits since it updates much less frequently than the git master counterpart.
Additionally it should have less sporadic breakage.

emacsGcc: Use the unstable emacs release for native compilation

---

default.nix
repos/emacs/emacs-feature_pgtk.json
repos/emacs/update

Pgtk feature has been merged to master and the feature/pgtk branch will stop being used (the configure script will fail unconditionally since [8627f735425c8bc97f57a1b7915e36221873862f](https://git.savannah.gnu.org/cgit/emacs.git/commit/?h=feature/pgtk&id=8627f735425c8bc97f57a1b7915e36221873862f)). It should be safe to merge the pull request after the next ci update.

emacsPgtk: Use the master branch for pgtk build

---

default.nix

Fixes installation of gui on darwin when nox is specified.
Closes #186 
Builds on x86_64-linux.

Use --without-ns for `nox` variants.

---

elisp.nix
packreq.nix

Fixes the dropped alias in PR https://github.com/NixOS/nixpkgs/pull/161146.

dropped alias: emacsPackagesGen -> emacsPackagesFor

---

elisp.nix
packreq.nix

Commit https://github.com/NixOS/nixpkgs/commit/a36f455905d55838a0d284656e096fbdb857cf3a removes aliases older the 2019-06-01, `emacsPackagesGen` was part of them.

'emacsPackagesGen' has been renamed to/replaced by 'emacsPackagesFor'

---

repos/elpa/test.nix
repos/emacs/test.nix
repos/exwm/test.nix
repos/melpa/test.nix

solves error `error: 'emacsPackagesNgGen' has been renamed to/replaced by 'emacsPackagesFor'`
should also solve #211 because the CI silently fails while updating the emacs and exwm repos
(see https://github.com/nix-community/emacs-overlay/runs/5504879838?check_suite_focus=true#step:6:2460 and https://github.com/nix-community/emacs-overlay/runs/5504879838?check_suite_focus=true#step:6:2622)
additionally renames old alias `emacsPackagesNg` to `emacsPackages`

rename emacsPackagesNgGen to emacsPackagesFor

---

repos/emacs/update

See #217 for motivation: With the current method, only tags which are reachable from `master` are fetched, because shallow commits are single branch by default. In particular, the `emacs-28.1` tag does not show up because the `emacs-28` branch has not been merged back to master.
Note that I use `emacs-[1-9]*` instead of `emacs-*` because there are old tags of the form `emacs-pretest-X.Y.Z` (for X <= 24) which mess up Git's tag sorting. Note that `git ls-remote --tags` uses globs, and therefore `[1-9]*` means "a digit followed by any number of characters", not "any number of digits".

Use git ls-remote to fetch latest tag

---

README.org
default.nix

In upstream nixpkgs PR https://github.com/NixOS/nixpkgs/pull/168076
native compilation support was introduced to the nixpkgs attribute.
This is a better naming more in line with upstream, so we should also
adopt it.
I have aliased emacsGcc to emacsNativeComp for backwards compatibility
with a trace notice informing users about the change.
Additionally we will now default to the upstream native comp derivation if it exists.

Change the emacsGcc attribute to emacsNativeComp

---

README.org
default.nix
hydra/emacsen.nix
repos/emacs/test.nix

As described in #222, this adds an emacs build from master with native compilation enabled, but without using pure GTK.
Additionally, I took the liberty to rename emacsPgtkGcc to emacsPgtkNativeComp to stay consistent with attribute naming.

Add emacsGitNativeComp attribute (#222)

---

default.nix

If I'm not mistaken, we should be using `super.emacs` instead of `self.emacs` here.  Using `self.emacs` causes infinite loops if I try to overlay `emacs` later on and refer to something out of `emacs-overlay` (i.e. I want to overlay `emacs` in nixpkgs to point to the pgtk build so that anything that refers to `pkgs.emacs` directly doesn't accidentally pull in some x build that breaks on wayland)
cc @adisbladis

Use `super.emacs` instead of `self.emacs`

---

default.nix
repos/emacs/emacs-master.json

This appears to fix the issue in https://github.com/nix-community/emacs-overlay/runs/8170666387?check_suite_focus=true#step:6:35752 when used in conjunction with https://github.com/NixOS/nixpkgs/pull/189929.

Use `withPgtk` option to fix failing `emacsPgtk` build

---

default.nix
repos/emacs/emacs-master.json

Reverts nix-community/emacs-overlay#240
@adisbladis I was intending for that other PR to be merged into here only after the unstable and 22.05 channels updated to contain https://github.com/NixOS/nixpkgs/pull/189939. I think the safe thing to do for now is to revert this PR. Sorry, I should have been clearer about the prerequisites.

Revert "Use `withPgtk` option to fix failing `emacsPgtk` build"

---

README.org

The issue has been closed for months and can be safely removed

README: Remove tracking nipkgs issue

---

default.nix

This should now be safe to merge since the stable channel has updated
to contain https://github.com/NixOS/nixpkgs/commit/01ec6cc8e9064f51f538428fdb7311bcc44927ea, and similar for the nixos-unstable channel. (BTW, you can verify that I got the number of Darwin rebuilds down to 0 in the end with a follow-up cherry-pick)
I tested by installing `emacsPgtk` on GNOME Wayland.
Some things I found that I think are OK but could use review:
1. With this commit, because of some of the changes I made in upstream
nixpkgs with some of the boolean logic involving `withPgtk` and
`withGTK3`, an installation of `emacsPgtk` running in X (as opposed to
Wayland) will now complain on about having trouble finding
`g_settings_schema_source_lookup`:
``` markdown
(emacs:5810): GLib-GIO-CRITICAL **: 22:20:33.963: …
```

Use upstream `withPgtk` input attribute and remove `mkPgtkEmacs`

---

default.nix

Reverts nix-community/emacs-overlay#247
Sorry about this. It seems I need to fix one more thing in [upstream Nixpkgs](https://github.com/nixos/nixpkgs/blob/3b5ee8a0baec8d8a3552b7d2098256af93d551e9/pkgs/applications/editors/emacs/generic.nix#L159-L162) before this can be merged.
Fixes https://github.com/nix-community/emacs-overlay/issues/248

Revert "Use upstream `withPgtk` input attribute and remove `mkPgtkEmacs`"

---

flake.nix

Before this patch and since #237, `overlayAttrs` is a list of all attrs in `all-packages.nix`, which breaks the usage of the `package` attr of this overlay.
But it should be only the attrs added by this overlay. This patch fixes this.

flake.nix: fix the hack of getting overlayAttrs

---

README.org
elisp.nix

This is good for AOT native compilation of user config.
Besides being bool, the value of this new option can also be a derivation produced by pkgs.substituteAll, which avoids IFD comparing to directly setting that derivation to the config param.
cc @leungbk

elisp.nix: add a param to include user config as a default init file

---

overlays/emacs.nix
repos/emacs/emacs-feature_tree-sitter.json
repos/emacs/test.nix
repos/emacs/update

Fixes #226 for Linux.
I don't have a Mac to get this to work and test it for Darwin. I _think_ it will be a matter of switching `.so` to the required extension.
Note, the dynamic libraries need to be set during the `buildPhase` otherwise the build fails. As more languages get added into emacs core, more `tree-sitter-grammars` need to be added.

Add `feature/tree-sitter` derivation to emacs overlay

---

flake.nix
overlays/default.nix

The old way of composing overlays addes an unnecessay overlay, which
breaks the packages attribute of the flake. To reduce the impact on
users, I make a workaround[1] for that, which has been merged. Now I
figure out the real fix, which is to change `(_: super)` to `(_: {})`.
Additionally, the old way is a bit confusing.
This patch fixes both issues by using a better and clearer way to
compose overlays.
Since the workaround is no longer needed after this patch, I revert
that in the next commit.
[1]: https://github.com/nix-community/emacs-overlay/pull/256
cc @leungbk

overlays: use a better and clearer way to compose overlays

---

overlays/emacs.nix
repos/emacs/emacs-lsp.json

Add support for https://github.com/emacs-lsp/emacs, an emacs with support for async JSONRPC based on latest stable making LSP way faster.

emacs: add emacsLsp

---

overlays/emacs.nix

resolves Issue #258
MacOS support for tree-sitter 
**Tests performed**
- PR has been tested on aarch64-darwin only. 
- Tests conducted using pkgs.emacsGitTreeSitter
- Tested twice with nativeComp enabled & disabled. 
- Verified build succeeds
- Verified emacs boots up 
- Verified M-x bash-ts-mode works
- Verified treesit-extra-load-path set correctly
- Verified (treesit-language-available-p 'bash) returns true 
**How to test it yourself**
```
nix shell --no-write-lock-file github:jasonjckn/emacs-overlay/issue-258\#emacsGitTreeSitter -c emacs --version
```
Special thanks to [c4710n](https://github.com/c4710n) for half the work here.

resolves Issue #258

---

overlays/emacs.nix

Follow up to my last PR, this is probably the correct way for dlopen/dynlib_open to locate the tree sitter parser *.so/*.dylib files, I believe this ought to work for both aarch64-darwin, and other *nix platforms, but i'll need someone to test it on x86.
I just ended up deleting the part that links the executable to the grammar shared objects, that seemed redundant to my current understanding. The purpose of doing a dlopen/dynlib_open is to dynamically load the shared objects at runtime. 
**How to test this branch**
```
nix build --refresh --recreate-lock-file --no-write-lock-file github:jasonjckn/emacs-overlay/rpath\#emacsGit
./result/bin/emacs --version
```
**Testing done on aarch64-darwin**
- bash-ts-mode works

add tree sitter languages to rpath

---

overlays/emacs.nix

This is the cross-platform way to add RPATH entries, which we can do since we run the emacs build, and it has the added benefit of working on Darwin (where adding the second rpath entry after CoreFoundation doesn't seem to be picked up, for some reason).
This fixes #289 for me.

Use build flags to add tree-sitter-grammars to RPATH on Darwin

---

overlays/package.nix

With the current implementation, changes to the nongnuPackages attr of the emacs package set don't propagate to the set's top level. By removing the special-casing for non-gnu, and adding it to the epkgs override like the other package sources, this fixes the issue.
Fixes #292 .

Remove special casing for nongnuPackages

---

flake.lock
flake.nix

Fixes #262.
This PR adds `nixpkgs` as an input to the flake. Previously, this flake used `nixpkgs` in its derivation without declaring it in the flake inputs. This caused the flake to depend on an arbitrary version of the package, resulting in cache misses for the downstream user. By adding `nixpkgs` to the flake inputs, users can lock the `nixpkgs` version of their flake to follow that of this package, thereby resolving the cache miss problem.
Furthermore, this change should not affect users of the overlay mechanism, since the overlays will be applied to the user's version of `nixpkgs`, not that declared in the flake.

Add nixpkgs input and create lock file

---

overlays/emacs.nix

I would like to be able to override the list of tree-sitter grammars.
Using these changes I can do this and it works:
```
pkgs.emacsPgtk.override {
treeSitterPlugins = with pkgs.tree-sitter-grammars; [
tree-sitter-elixir
tree-sitter-heex
];
};
```
This issue is related: https://github.com/nix-community/emacs-overlay/issues/274

allow tree-sitter grammars to be overridden

---

flake.nix

`emacsPackagesFor`, `emacsWithPackagesFromPackageRequires`, `emacsWithPackagesFromUsePackage` were omitted from the `packages` output because they aren’t derivations. Expose them via a new `lib` output to enable using them without the overlay.

flake: Add `emacsPackagesFor`, `emacsWithPackages*` to `lib` output

---

overlays/emacs.nix

html-ts-mode is built-in in GNU Emacs. Thus, add html grammar.

add tree-sitter-html

---

hydra/default.nix
hydra/spec.json

builds are pushed to cachix so keeping multiple evaluations is unnecessary.
cc @Mic92

hydra: keep one evaluation only

---

flake.nix

Enables the nix CLI to prompt the user to enable the flake's cache. (`nix run`, `nix profile install` etc)
Currently, the settings are stored to the user's nix.conf, so they're not scoped to the current run, but that may change down the road.  
The nixConfig is ignored when the flake is listed as an input to another flake (but again, tooling could solve this, eg by generating flake.nix.
I don't seem to be getting cache hits with the flake though, but that is orthogonal.

flake: add nixConfig for build cache

---

overlays/emacs.nix

Now that emacsUnstable is Emacs 29.0.90, we can add the pgtk variant.

Add emacsUnstablePgtk

---

README.org
elisp.nix
packreq.nix

This fixes an issue that override cannot override packages which are the dependencies of usePkgs and not in usePkgs.
This also preserves backward compatibility of override.  The hash of the generated Emacs package from emacsWithPackagesFromUsePackage does not change after this patch is applied using the old style override.

Use overrideScope' for override

---

README.org

Hi after, trying to use the example code. I noticed that it was missing either the 'pkgs.' at the start of the package name, or the 'with pkgs' before the list of package names. I added the 'pkgs.' to the package name as that is what was used in the other example. To try and make the examples more consistent and easier to use.

added missing 'pkgs.' at start of package name for example.

---

overlays/package.nix
repos/elpa/elpa-devel-generated.nix
repos/elpa/update

Some packages are not currently fetched since something upstream of us (maybe `emacs2nix`?) doesn't properly handle version names with letters in their names. For example,
``` markdown
+ rm elpa-devel-generated.nix
++ nix-instantiate --eval --expr 'let nixpath = builtins.toString (import <nixpkgs> {}).path; in "${nixpath}/pkgs/applications/editors/emacs
/elisp-packages/update-elpa-devel"'
+ eval '"/nix/store/w5nllnx445dvyhzxbnb8z92k8zn4ab2k-nixos/nixos/pkgs/applications/editors/emacs/elisp-packages/update-elpa-devel"'
++ /nix/store/w5nllnx445dvyhzxbnb8z92k8zn4ab2k-nixos/nixos/pkgs/applications/editors/emacs/elisp-packages/update-elpa-devel
in process nix-prefetch-url 'https://elpa.gnu.org/devel/erc-5.6.-4.0.20230530.154453.tar': died with exit code 1:
error: unable to download …
```

Add elpaDevelPackages

---

overlays/emacs.nix
repos/emacs/commercial-emacs-commercial-emacs.json
repos/emacs/update

Despite the name, this is still GPL-licensed. [commercial-emacs/commercial-emacs](https://github.com/commercial-emacs/commercial-emacs).
Unfortunately, I wasn't able to get the tree-sitter override to work, which is why that's disabled for now.

Add commercial-emacs attribute

---

overlays/emacs.nix

On nixos-unstable, I see several repetitions of the following warning when running `nix flake check` in my personal config:
```
trace: warning: nativeComp option is deprecated and will be removed; use withNativeCompilation instead
```
Edit: ~The `commercial-emacs` package defined here is the only result I found for occurrences of `nativeComp` in my flake or its inputs.~ I didn’t find any occurrences of `nativeComp` in my own repo.

commercial-emacs: replace deprecated nativeComp attribute

---

.github/workflows/ci.yml

This reverts commit c0ef7074c168adcb5f4038d9848eaedaeb5a27bc because [NixOS/nixpkgs#276943 has been merged into nixos-unstable](https://nixpk.gs/pr-tracker.html?pr=276943).
cc: @leungbk

Revert "Temporarily disable "emacs" update"

---

repos/melpa/recipes-archive-melpa.json

Fixes https://github.com/nix-community/emacs-overlay/issues/384
The geiser package hash is incorrect, and this sets it to the correct value.
While this file is autogenerated, perhaps it had some networking issue when generating the file?
I tried re-running the update script locally to test, but it gets stuck on my machine and does not get to updating the file.

Fix geiser hash

---

overlays/emacs.nix

Previously, using the Emacsen where bytecomp-revert.patch is applied could cause a costly cache miss, because `(emacs-attr).pkgs.emacs` was not updated to be equal to `(emacs-attr)`; instead, it remained as the unpatched version. This commit fixes that.
This was an issue if, for instance, one tried to install from `(emacs-attr).pkgs.*` directly into a profile/system. An Emacs without the patch would be depended upon, but that's not built by CI it seems, as nix would try to build it from scratch. I tested this with `packages.x86_64-linux.emacs-pgtk` vs. `packages.x86_64-linux.emacs-pgtk.pkgs.emacs`, the latter lacked the patch prior to this commit, whereas the former got pulled from cache.

Fix cache miss due to bytecomp-revert

---

repos/melpa/recipes-archive-melpa.json

Reverts nix-community/emacs-overlay#397
From the discussion in https://github.com/nix-community/emacs-overlay/issues/391 it looks like only Darwin systems had the invalid hash, this PR reverts the hash change in order to correct Linux systems.
I'll leave it to the maintainers on which OS should be broken while a actual hash correction is figured out.

Revert "Correct SmartParens hash" (Fix Linux break Darwin)

---

flake.nix

In addition, use a better name for stable hydra jobs.

flake: bump nixpkgs-stable to 24.05

---

flake.nix

We have an aarch64-linux builder. https://github.com/nix-community/infra/blob/master/devdoc/hosts.md#build04

flake: drop aarch64-linux cross and build native

---

repos/melpa/recipes-archive-melpa.json

Encountered an error while building `emacs-geiser`.
```
error: hash mismatch in fixed-output derivation '/nix/store/wqgzvkivjc1pwvh7l44n2fc9d3xy1ls0-source.drv':
specified: sha256-fC4dEWvMiDVx7P8dLrX5CVvR5QZyj383V9lV1bxryPM=
got:   sha256-NSrXGtedpXxNTu/5qd92ocAIqOUeXC6FmbplrMg+KI8=
```
If others encounter this as well, it can be merged here to fix.

recipes-archive-melpa: fix incorrect source hash of geiser

---

overlays/emacs.nix

See upstream bug https://lists.gnu.org/archive/html/bug-gnu-emacs/2024-09/msg00695.html
I submitted https://github.com/NixOS/nixpkgs/pull/344631 to the `staging` branch of nixpkgs, but since it may take a while for that to make its way into the unstable branch, I figured we could make the change here and revert later since the `webkitgtk` rejection during the `configure` phase is preventing the Emacs and MELPA jobs here from finishing.
closes https://github.com/nix-community/emacs-overlay/issues/426

Disable webkit2gtk integration

---

repos/emacs/update

For example, see https://github.com/nix-community/emacs-overlay/actions/runs/11165733178/job/31038160001#step:6:350

Adapt Emacs update script to chop off more extraneous info

---

flake.nix

The update of `flake.lock` is left to be done by CI to avoid merge conflicts.

flake: bump nixpkgs-stable from 24.05 to 24.11

---

README.org

Inspired by [`mu4e`'s recipe](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/elisp-packages/manual-packages/mu4e/package.nix#L13)
Now here's a lil issue i'd love to resolve:
- if you `nix build|run` such a closure, `extraPackages` won't be available
- only when this closure is installed (with `nix profile install` or adding it to `environment.systemPackages`/`home.packages`), `extraPackages` can be propagated.\*
Is this behaviour fine as is or should I make `extraPackages` always available?
\*Just tried with `nixos-rebuild test`, somehow this doesn't work :thinking:

README: clarify `extraEmacsPackages` usage

---

overlays/emacs.nix

This reverts commit ce4ed6b670743b22ae3816b24cd3e72818246aad.
The needed change has reached stable and unstable Nixpkgs channels. No need to duplicate it here now.

Revert "Disable webkit2gtk integration"

---

overlays/emacs.nix

This reverts commit 8823d476190cdaebc8d6c8bcf664b0179935e20d.
Due to the way the default values of withFoo flags are specified and the way Emacs variants are overridden, default values of those flags in this overlay may be incorrect.
This commit is a workaround.  We should do a proper fix later.

Reapply "Disable webkit2gtk integration"

---

flake.nix
overlays/emacs.nix
repos/emacs/emacs-feature_igc.json
repos/emacs/test.nix
repos/emacs/update

This pull request adds Emacs builds with the incremental garbage collector being developed on Emacs "feature/igc" branch.
The source repos/emacs/emacs-igc.json is currently fetched using `update_github_repo` because savannah returns a "429 Too Many Requests" for me currently (no matter the VPN).
The "--with-mps=yes" flag can also take the values "debug" or "no" and one could possibly add a new derivation input for this (like I do [here](https://github.com/naveen-seth/emacs-igc-overlay/blob/08158e9156d08085f289c3acca92bec9f25fe63f/flake.nix)).
I left that out for now to better fit with the current pattern.

Add emacs-igc and emacs-igc-pgtk

---

repos/emacs/emacs-unstable.json
repos/emacs/update
repos/emacs/update-unstable.py

So that we can use https://packaging.pypa.io/en/latest/version.html to parse/sort version numbers correctly for `-rc` releases.
See https://github.com/nix-community/emacs-overlay/issues/470#issuecomment-2695930027.

repos/emacs: Rewrite unstable updater using Python

---

overlays/emacs.nix

In the future, emacs-pgtk will be removed and after that it will point to the one[1] in Nixpkgs.
[1]: https://github.com/NixOS/nixpkgs/commit/4347ffbee0581f4bdac825a9c912580cea76c96d

overlays/emacs: rename emacs-pgtk to emacs-git-pgtk

---

.github/workflows/ci.yml
.github/workflows/pulls.yml

https://github.com/nix-community/emacs-overlay/issues/474
cachix/install-nix-action@v30 [by default](https://github.com/cachix/install-nix-action/blob/08dcb3a5e62fa31e2da3d490afc4176ef55ecd72/install-nix.sh#L96) installs nix-2.24.9, which has bug https://github.com/NixOS/nix/issues/11681.

.github: pin Nix 2.24.12 for CI

---

repos/melpa/recipes-archive-melpa.json

https://hydra.nix-community.org/build/4840731
Hopefully, this is the last hash fix with https://github.com/NixOS/nixpkgs/pull/397761 merged.

forge-llm: fix src hash

---

README.org

`emacsGit` was replaced by `emacs-git` on fdf09998a0484722757cfd5672a8b745bec982bb.

README.org: handle obsolete symbol `emacsGit`

---

overlays/emacs.nix

Users have been notified for about 4 months[1] which should be long enough.
This is the second and last PR for #471.  Fixes #471.
[1]: #473

Remove emacs-pgtk to not shadow the one from Nixpkgs
