README.org
default.nix
repos/elpa/elpa-generated.nix
repos/elpa/test.nix
repos/elpa/update
repos/org/test.nix
repos/org/update

Waiting for https://github.com/NixOS/nixpkgs/pull/66819 to reach unstable before merging
Closes #1 
Closes #2

Add elpa/org package sets

---

README.org

These were the things I needed to look for after arriving in this repository

added some discoverability

---

default.nix

The flag `--with-json` is on by default

Add jansson to buildInputs

---

README.org
default.nix

I believe that this will resolve #10.
This works fine on my system at least :)

Add emacsGit-nox

---

flake.nix

Tested with my flake-based system config—works fine.

Add flake.nix

---

parse.nix

fixes #48.
Builds successfully, although whether this is the right approach is a question for more experienced nix users.

use fixed package set

---

default.nix

See https://github.com/NixOS/nixpkgs/pull/93716
Closes #33
Closes #35
Closes #37
Closes #39

emacsGit/emacsGcc: Use nativeComp support from nixpkgs

---

repos/elpa/elpa-generated.nix

Update repos/elpa manually in lieu of ci

---

hydra/emacsen.nix

Add hydra jobsets for pgtk builds

---

default.nix

Does what it says on the tin :)

Fix passthru packagesets of built emacs drvs

---

elisp.nix

This PR adjusts the default for `alwaysEnsure` to be null, picking a useful default and displaying a warning about the changed default. 
This fixes #117.
Here you go, @adisbladis (:

Remove warning about alwaysEnsure if alwaysEnsure was passed

---

README.org
repos/emacs/emacs-master.json

Updated with a quick start section

Add Quickstart section to README.org

---

repos/elpa/update
repos/melpa/update
repos/org/update

* repos/elpa/update: Update.
* repos/melpa/update: Update.
* repos/org/update: Update.
See nixpkgs commit
https://github.com/NixOS/nixpkgs/commit/70a5cbc2987b61e2c964c3390cffcedf394de1ad.
Closes #158.

emacs-modes -> emacs/elisp-packages

---

default.nix
repos/nongnu/nongnu-generated.nix
repos/nongnu/test.nix
repos/nongnu/update

Fix: #155 
Related: ttuegel/emacs2nix#59 and nixos/nixpkgs#126807

Add nongnu elpa

---

default.nix

Depends on https://github.com/NixOS/nixpkgs/pull/150507

Add sqlite3 support for Emacs 29

---

default.nix

Enable withGTK3 flag for emacs-pgtk derivations

---

repos/emacs/emacs-lsp.json

Related to https://github.com/emacs-lsp/emacs/issues/1

Bump emacs-lsp

---

hydra/default.nix

Resolves #276 if I correctly understood the Hydra setup.

chore(Hydra): Changed stable: 22.05 -> 22.11

---

overlays/emacs.nix

fixes segfaults that only occur on aarch64-linux (issue #264)

---

overlays/emacs.nix

Use withPgtk = true in emacsPgtk

---

overlays/emacs.nix

Build emacsGit without Xcode

---

overlays/emacs.nix

https://github.com/NixOS/nixpkgs/commit/6c209e862e18d6a9d103a80d5fa2443f4e47163e

Path fixes resulting from libgccjit changes

---

overlays/emacs.nix

Account for nixpkgs checkouts that don't have withTreeSitter argument

---

flake.nix
overlays/emacs.nix

https://github.com/NixOS/nixpkgs/pull/233301

Align with nixpkgs attribute syntax since https://github.com/NixOS/nixpkgs/pull/233301

---

elisp.nix

It's been around for long enough by now.

Remove ensure API breakage notice

---

elisp.nix

Fixes https://github.com/nix-community/emacs-overlay/issues/356
The second commit is a minor improvement and unrelated to the issue to be fixed.

Fix default.el version

---

.github/workflows/ci.yml
.github/workflows/pulls.yml
flake.nix

This may fix some warning in recent github actions.

Update github action deps and nixpkgs-stable

---

.github/workflows/ci.yml

Successful Action: https://github.com/Vonfry/emacs-overlay/actions/runs/7397127035 on [branch](https://github.com/Vonfry/emacs-overlay/commits/ci-trial/)
Fix #375.

Reset GIT_PAGER in CI

---

elisp.nix

elisp: Tangle org-mode files when used with defaultInitFile

---

README.org

README: emacsGit is deprecated, replace it with emacs-git

---

repos/melpa/recipes-archive-melpa.json

Related to #391
Inspired by #387

Correct SmartParens hash

---

repos/melpa/recipes-archive-melpa.json

maybe close https://github.com/nix-community/emacs-overlay/issues/391

recipes-archive-melpa: fix incorrect source hashes

---

overlays/package.nix
repos/nongnu/nongnu-devel-generated.nix
repos/nongnu/update

depends on https://github.com/NixOS/nixpkgs/pull/331051
do not merge until that PR reaches both the [stable][2] and [unstable][1] channel
[1]: https://github.com/NixOS/nixpkgs/pull/331051
[2]: https://github.com/NixOS/nixpkgs/pull/331072
Closes #371

Add nongnuDevelPackages

---

overlays/emacs.nix

Use bytecomp-revert.patch for unstable Emacsen

---

overlays/emacs.nix

remove: withGTK2, see #431

---

repos/melpa/recipes-archive-melpa.json

https://hydra.nix-community.org/build/1412093
https://hydra.nix-community.org/build/1408069
https://hydra.nix-community.org/build/1412083

recipes-archive-melpa.json: fix hashes for timu-*-theme

---

repos/emacs/update

Disable emacs-unstable update

---

repos/melpa/recipes-archive-melpa.json

https://hydra.nix-community.org/build/2761029

Fix src hash for timu-macos-theme

---

repos/melpa/recipes-archive-melpa.json

https://hydra.nix-community.org/build/4065903

starhugger: fix src hash

---

repos/melpa/recipes-archive-melpa.json

https://hydra.nix-community.org/build/4282942

org-re-reveal: fix src hash

---

repos/melpa/recipes-archive-melpa.json

https://hydra.nix-community.org/build/4424623

python-mode: fix src hash

---

repos/emacs/update

follow savannah redirect for atom feed
